
GET http://localhost:4000/tecnologias

###
GET http://localhost:4000/tecnologias/destaques

###
POST http://localhost:3000/tecnologias
Content-Type: application/json
{
    "nome": "Node.js",
    "descricao": "JavaScript runtime built on Chrome's V8 JavaScript engine.",
    "link": "https://nodejs.org",
    "imagem": "https://nodejs.org/static/images/logo.svg"
}
